name: hola-mundo
on: [push]

jobs:
  hola-mundo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: intall Go
        uses: actions/setup-go@v4
      - run: go version
      - run: go run hola-mundo.go
